prometheus:
  prometheusSpec:
    scrapeConfigs:
      - job_name: "hotel-app"
        metrics_path: /metrics
        static_configs:
          - targets: ["hotel-service.default.svc.cluster.local:5000"]
