apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-app
  template:
    metadata:
      labels:
        app: hotel-app
    spec:
      containers:
        - name: hotel-app
          image: 278338841334.dkr.ecr.ap-south-2.amazonaws.com/hotel-management-repo:latest
          ports:
            - containerPort: 5000
